Add message that SRV check was skipped if .well-known is configured
matrix-org/fed-tester-ui pull request #26
Opened 2021-01-15 22:09 UTC by hamburghammer

The backend does not check for the SRV records if a .well-known
configuration with a port declaration was found. It will return an
empty SRVRecords field which leads to the understanding that nothing
was found even though it was intentionally skipped. The newly introduced
message will inform the user that it was skipped because a .well-known
configuration was found.

Tries to resolve #25 

Refs:
- https://github.com/matrix-org/matrix-federation-tester/issues/104

2021-01-26 13:42 UTC, erikjohnston commented on app.js
> +    if (wellknown["m.server"].includes(":")) {
Technically this should also check if its an IP address too.

2021-01-27 08:58 UTC, hamburghammer commented on app.js
> +    if (wellknown["m.server"].includes(":")) {
If I understand you correctly you think that it should also check for valid:
- IPv4 address
- IPv6 address
- domain name
The current implementation defensively does not work with IPv6, but should I add for all three cases a regex validation?

2021-04-14 17:26 UTC, hamburghammer commented
@erikjohnston The check know supports IPv6 addresses as well as IPv4 and domains.

2021-04-16 11:07 UTC, richvdh reviewed
hrm. I appreciate the contribution, but I feel like this is the wrong approach - it infers too much about the backend's behaviour based on heuristics.

I'd much prefer it if we could update the backend to return something in the JSON to indicate that SRV lookup was skipped, so that we can use that here.

How's your Golang? :innocent:

2021-04-20 12:46 UTC, hamburghammer commented
I just did a rebase for a cleaner commit history.
It now contains the changes to use the new `SRVSkipped` field.

2021-04-21 12:58 UTC, richvdh requested changes
thank you! I think we can make this more accurate though.

2021-04-21 12:58 UTC, richvdh commented on app.js
> +          <h2>.well-known information found -&gt; SRV record-check skipped</h2>
This isn't really accurate.

```suggestion
          <h2>server name/.well-known result contains explicit port number: no SRV lookup done</h2>
```

2021-04-21 12:58 UTC, richvdh commented on app.js
> +          <h2>.well-known information found -&gt; SRV record-check skipped</h2>
Also: h2 is a bit big: it looks like an error of some kind. Shouldn't this be in a "DNS results" section, with smaller text saying that we skipped SRV lookup?

(The existing `if (j.SRVRecords == null)` logic is wrong too, but there is no need to make the problem worse)

2021-04-21 12:58 UTC, richvdh commented on app.js
> +      return (
why do we omit the data from `Hosts` in this case? There is still useful information there.

2021-04-28 09:03 UTC, hamburghammer commented on app.js
> +      return (
The Hosts that are shown in this case are the IP of the Host found inside the `.well-known` file. This IP is already listed inside the connection results list, I am currently looking to add a table showing the found Hostname and the resolved IP to give at leased some context to the `Address` list.
I have currently not that much time 🙈 but will try to find a slot this week to update this PR

2021-07-30 23:03 UTC, hamburghammer commented
@richvdh 
Sorry for my absents, but I finally found some time to work on this PR. Thanks for not closing it in the mean time.
I had to do some changes to the way the DNS results where displayed and I'm not sure if it's the best possible way to do it, but I am quiet happy with the result.

2021-08-03 12:53 UTC, richvdh requested changes
Thank you for revisiting this! I think it's taking shape, but it's a bit hard to follow at the moment. I've made a few suggestions below.

2021-08-03 12:53 UTC, richvdh commented on app.js
> +    let dnsResultTitle = <> <h3>DNS records for {j.SRVCName}</h3> </>
note that the `<> ... </>` is redundant here:

```suggestion
    let dnsResultTitle = <h3>DNS records for {j.SRVCName}</h3>;
```

2021-08-03 12:53 UTC, richvdh commented on app.js
>          <div className="table">
why not include this `<div className="table">` inside `records`? (also: it would probably make sense to include `dnsResultTitle` too.)

2021-08-03 12:53 UTC, richvdh commented on app.js
> +    let records;
I think it would make more sense to call this `srv_records_table` or something. `records` is very undescriptive.

2021-08-03 12:53 UTC, richvdh commented on app.js
> +          <h3>DNS records</h3>
It looks like this will give us ` <h2>DNS results</h2>` immediately followed by `<h3>DNS records</h3>`.  This doesn't seem to make much sense. Why do we need an extra heading in this case?

2021-08-03 12:53 UTC, richvdh commented on app.js
> +            <h3>{host}</h3>
while you're changing this: I think it would make sense to include the `Error` for each `Host` under the same heading, rather than having a separate section for errors.

2021-08-24 10:03 UTC, richvdh commented
@hamburghammer it would be great if you could find time to put the finishing touches to this PR soon?

2021-08-24 19:43 UTC, hamburghammer commented on app.js
> +          <h3>DNS records</h3>
I overlooked it :see_no_evil: It wasn't intended

2021-08-24 19:45 UTC, hamburghammer commented on app.js
> +    let records;
I renamed it to `srvRecordsTable` to match the naming style

2021-08-24 19:47 UTC, hamburghammer commented on app.js
>          <div className="table">
To move this into `records` makes sense to me, but I don't understand why it should be included inside the `dnsResultTitle`?

2021-08-24 19:54 UTC, hamburghammer commented on app.js
> +            <h3>{host}</h3>
This wasn't that easy for me to archive. I did a rather large refactoring to archive the composition of the `Host` table to include the `Error` table. It should also not render an empty table if no values are provided for `Host` or `Error`. To implement it I had to create a rather unsexy if/else check chain...

2021-09-02 10:05 UTC, hamburghammer commented on app.js
>          <div className="table">
The styling gets applied anyways, but I changed it to make it explicit.

2021-09-03 11:18 UTC, richvdh commented on app.js
> +        const addresses = function() {
I think at least one of these layers of `function()`s is redundant, but it's fine I guess.

2021-09-03 12:31 UTC, richvdh requested changes

2021-09-03 12:31 UTC, richvdh commented on app.js
> +        const recordRows = j.SRVRecords.map((record, id) => {
I've been doing some testing on this, and generally it now looks great for servers with SRV records, and those where the SRV lookup is skipped.

However, there is a third case we're not correctly handling, which is when the SRV lookup is not skipped, but there are no SRV records - see for example the results for `sw1v.org`:

![image](https://user-images.githubusercontent.com/1389908/132004647-dcfb71ec-4ce2-48b6-8c35-20d546c55b21.png)

In this case, `SRVSkipped` is false, but `SRVCName` is `""` and `SRVRecords` is `null`.

How about moving the logic for the title into this function:

```suggestion
    const srvRecordsTable = function() {
      if (j.SRVSkipped) {
        return <p>server name/.well-known result contains explicit port number: no SRV lookup done</p>;
      } else if (j.SRVRecords == null) {
        return <p>No SRV records found</p>;
      } else { 
        const recordRows = j.SRVRecords.map((record, id) => {
```

(and add `<h3>DNS records for {j.SRVCName}</h3>` further down)

Then `srvResultTitle` and friends can be removed.

2021-09-07 19:54 UTC, hamburghammer commented on app.js
> +        const recordRows = j.SRVRecords.map((record, id) => {
This looks defensively weird. Thx for catching it :see_no_evil:

2021-09-08 09:58 UTC, richvdh approved these changes
This looks great now. Thank you so much for your perseverance!

2021-09-08 10:01 UTC, merged